language: csharp

dist: trusty

sudo: required

solution: Foodery/Foodery.sln

branches:
  only:
    - master

install:
  - curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  - sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
  - sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-artful-prod artful main" > /etc/apt/sources.list.d/dotnetdev.list'

script:
  - dotnet restore ./Foodery/Foodery.sln
  - dotnet build ./Foodery/Foodery.sln
  - dotnet test ./Foodery/Foodery/Tests/Unit/Foodery.Unit.Tests/Foodery.Unit.Tests.csproj