language: csharp

dist: trusty

sudo: required

solution: Foodery/Foodery.sln

mono: none

dotnet: 2.0.0

branches:
  only:
    - master

script:
  - dotnet restore ./Foodery/Foodery.sln
  - dotnet build ./Foodery/Foodery.sln -c Release
  - dotnet test ./Foodery/Tests/Unit/Foodery.Tests.Unit.Web/Foodery.Tests.Unit.Web.csproj -c Release